### ISSUE TITLE
数据查询调用http接口返回失败

### ISSUE THREAD

**Issue by knowledge-things** [xuwei95/ezdata#2]
接口接受json格式，postman模拟可以，但是通过数据查询界面提供的功能发送请求服务端不能正常解析，想请教下具体的请求流程是如何处理的

**Comment by xuwei95** [comment]
数据查询是根据数据模型对应的数据源和查询表单配置，组合得到对应查询配置后查询对应数据源并返回的，具体可提供报错截图等查看原因。
